# Generated by Django 5.2.11 on 2026-02-04 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nama_status', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori', models.ForeignKey(db_column='kategori_id', on_delete=django.db.models.deletion.CASCADE, to='products.kategori')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='products.status')),
            ],
            options={
                'db_table': 'produk',
            },
        ),
    ]
