# Generated by Django 5.2.11 on 2026-02-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='id_produk',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
